*CELL NÀY GIỮ CỐ ĐỊNH

In [1]:
# Libraries
import numpy as np
import pandas as pd
from charset_normalizer.cd import encoding_unicode_range
from sklearn import *
# Preprocessing
from src.preprocessing import *
from src.preprocessing import run_phase_1_cleaning

path = "..\\data\\jewelry.csv"
column_names = [
    'event_time',    # Thời gian mua hàng
    'order_id',      # Mã đơn hàng
    'product_id',    # Mã sản phẩm
    'quantity',      # Số lượng
    'category_id',   # Mã danh mục
    'category_code', # Tên loại trang sức
    'brand_id',      # Mã thương hiệu
    'price',         # Giá tiền
    'user_id',       # Mã khách hàng
    'gender',        # Giới tính
    'color',         # Màu sắc (red, white, gold...)
    'metal',         # Chất liệu kim loại (gold, silver...)
    'gem'            # Loại đá quý (diamond, sapphire...)
]

# Ép về string
# tránh đề string dài quá đọc csv sẽ tự chuyển sang int64
dtype_specs = {
    'order_id': str,
    'product_id': str,
    'category_id': str,
    'brand_id': str,
    'user_id': str,
    'category_code': str
}
dataset = pd.read_csv(path, header=None, names=column_names, dtype=dtype_specs)

In [12]:
dataset.info()

<class 'pandas.DataFrame'>
Index: 90559 entries, 0 to 95910
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     90559 non-null  datetime64[us, UTC]
 1   order_id       90559 non-null  str
 2   product_id     90559 non-null  str
 3   quantity       90559 non-null  int64
 4   category_id    90559 non-null  str
 5   category_code  90559 non-null  str
 6   brand_id       90559 non-null  str
 7   price          90559 non-null  float64
 8   user_id        90559 non-null  str
 9   gender         90559 non-null  str
 10  color          90559 non-null  str
 11  metal          90559 non-null  str
 12  gem            90559 non-null  str
dtypes: datetime64[us, UTC](1), float64(1), int64(1), str(10)
memory usage: 9.7 MB

In [17]:
# def format_datetime_column(df: pd.DataFrame) -> pd.DataFrame:
#     if 'event_time' in df.columns:
#         df['event_time'] = pd.to_datetime(df['event_time'], errors='coerce')
#     return df

dataset = format_id_columns(dataset)
dataset = format_datetime_column(dataset)
dataset.info()
dataset.head(4)

<class 'pandas.DataFrame'>
Index: 90559 entries, 0 to 95910
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     90559 non-null  datetime64[us, UTC]
 1   order_id       90559 non-null  str
 2   product_id     90559 non-null  str
 3   quantity       90559 non-null  int64
 4   category_id    90559 non-null  str
 5   category_code  90559 non-null  str
 6   brand_id       90559 non-null  str
 7   price          90559 non-null  float64
 8   user_id        90559 non-null  str
 9   gender         90559 non-null  str
 10  color          90559 non-null  str
 11  metal          90559 non-null  str
 12  gem            90559 non-null  str
dtypes: datetime64[us, UTC](1), float64(1), int64(1), str(10)
memory usage: 9.7 MB

,event_time,order_id,product_id,quantity,category_id,category_code,brand_id,price,user_id,gender,color,metal,gem
0,2018-12-01 11:40:29+00:00,1924719191579951782,1842195256808833386,1,1806829201890738522,earring,0,561.51,1515915625207851155,unknown,red,gold,diamond
1,2018-12-01 17:38:31+00:00,1924899396621697920,1806829193678291446,1,1806829201848795479,unknown,unknown,212.14,1515915625071969944,unknown,yellow,gold,unknown
2,2018-12-02 13:53:42+00:00,1925511016616034733,1842214461889315556,1,1806829201915904347,pendant,1,54.66,1515915625048493557,f,white,gold,sapphire
3,2018-12-02 17:44:02+00:00,1925626951238681511,1835566849434059453,1,1806829201915904347,pendant,0,88.90,1515915625207630915,f,red,gold,diamond

In [8]:
def format_price_column(df: pd.DataFrame) -> pd.DataFrame:
    if 'price' in df.columns:
        df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0.0)

In [5]:
dataset = clean_category_column(dataset)
dataset = clean_product_attributes(dataset)
dataset.head(5)
dataset.shape

(95911, 13)

SAU KHI LOẠI BỎ CÁC HÀNG DỮ LIỆU BỊ THIẾU ĐỊNH DANH

In [6]:
dataset = drop_missing_critical_ids(dataset)
dataset.shape

(90559, 13)

In [19]:
dataset = run_phase_1_cleaning(dataset)
dataset.shape
dataset.head(5)

,event_time,order_id,product_id,quantity,category_id,category_code,brand_id,price,user_id,gender,color,metal,gem
0,2018-12-01 11:40:29+00:00,1924719191579951782,1842195256808833386,1,1806829201890738522,earring,0,561.51,1515915625207851155,unknown,red,gold,diamond
1,2018-12-01 17:38:31+00:00,1924899396621697920,1806829193678291446,1,1806829201848795479,unknown,unknown,212.14,1515915625071969944,unknown,yellow,gold,unknown
2,2018-12-02 13:53:42+00:00,1925511016616034733,1842214461889315556,1,1806829201915904347,pendant,1,54.66,1515915625048493557,f,white,gold,sapphire
3,2018-12-02 17:44:02+00:00,1925626951238681511,1835566849434059453,1,1806829201915904347,pendant,0,88.90,1515915625207630915,f,red,gold,diamond
4,2018-12-02 21:30:19+00:00,1925740842841014667,1873936840742928865,1,1806829201924292956,necklace,0,417.67,1515915625175329378,unknown,red,gold,amethyst